### ISSUE TITLE
incompatible with underscore 1.4

### ISSUE THREAD

**Issue by RicoP** [szabyg/annotate.js#22]
Underscore.js renamed the _.intersect function to _.intersection. My bugfix will fix this issue  96b643feeae11e062054dda5a3d7b7d6a8e37754

**Comment by RicoP** [comment]
I also updated the underscore version in the example 485af9322c4dcb34648cb53ccbbb8a5a26d4e329

**Comment by szabyg** [comment]
Thanks! This issue and a couple more are fixed since last week though.
