### ISSUE TITLE
Disambiguation popup displayed to far to the right

### ISSUE THREAD

**Issue by akuckartz** [szabyg/annotate.js#26]
In the example http://szabyg.github.com/annotate.js/ the disambiguation popup is displayed to far to the right for text which is near the right border. Disambiguation therefore is not possible.

**Comment by akuckartz** [comment]
Thanks!

(The position is still not optimal but it now is completely visible :-)

**Comment by szabyg** [comment]
Thanks for reporting! The positioning is from [jQuery UI position](http://api.jqueryui.com/position/). If you find a better settings, let me know!
